CREATE TABLE `FLT` (
	`flt_no`	VARCHAR(10)	NOT NULL,
	`flt_date`	DATE	NOT NULL,
	`craft_id`	VARCHAR(10)	NOT NULL	DEFAULT "A380",
	`flt_bound`	VARCHAR(3)	NOT NULL	DEFAULT "DOM",
	`flt_stat`	VARCHAR(15)	NULL	DEFAULT "ARRIVED",
	`flt_sta`	TIME(0)	NULL,
	`flt_std`	TIME(0)	NULL,
	`flt_dpt`	VARCHAR(5)	NOT NULL,
	`flt_arr`	VARCHAR(5)	NOT NULL,
	`flt_airline`	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (flt_no`,`flt_date`)
);

CREATE TABLE `PAX` (
	`pax_uid`	BIGINT	NOT NULL,
	`rsv_no`	VARCHAR(10)	NOT NULL,
	`pax_pspt`	VARCHAR(10)	NULL	DEFAULT "M11122333",
	`pax_name`	VARCHAR(50)	NOT NULL,
	`pax_birth`	DATE	NOT NULL,
	`pax_age`	VARCHAR(5)	NULL	DEFAULT "ADLT"
);

CREATE TABLE `GS` (
	`gs_id`	VARCHAR(10)	NOT NULL,
	`gs_pw`	VARCHAR(64)	NOT NULL,
	`gs_auth`	INT	NOT NULL,
	`gs_airline`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `BGG` (
	`chkin_id`	BIGINT	NOT NULL,
	`bgg_weight`	INT	NOT NULL	DEFAULT 15,
	`bgg_trans`	BOOL	NULL	DEFAULT 0,
	`bgg_dmg`	BOOL	NULL	DEFAULT 0,
	`bgg_heavy`	BOOL	NULL	DEFAULT 0,
	`bgg_frag`	BOOL	NULL	DEFAULT 0
);

CREATE TABLE `CHKIN` (
	`chkin_id`	BIGINT	NOT NULL,
	`flt_date`	DATE	NULL,
	`flt_no`	VARCHAR(10)	NULL,
	`pax_uid`	BIGINT	NOT NULL,
	`chk_seat`	VARCHAR(3)	NULL,
	`chk_memo`	VARCHAR(200)	NULL	DEFAULT "NIL",
	`chk_stat`	VARCHAR(10)	NULL	DEFAULT "RSV",
	`chk_ssr`	VARCHAR(50)	NULL	DEFAULT "NIL"
);

CREATE TABLE `RSV` (
	`rsv_no`	VARCHAR(10)	NOT NULL,
	`rsv_cost`	INT	NULL	DEFAULT 1000
);

CREATE TABLE `CRAFT` (
	`craft_id`	VARCHAR(10)	NOT NULL	DEFAULT "A380",
	`craft_cap`	INT	NULL	DEFAULT 132
);

CREATE TABLE `LOG` (
	`log_id`	INT	NOT NULL,
	`gs_id`	VARCHAR(10)	NOT NULL,
	`chkin_id`	BIGINT	NOT NULL,
	`log_history`	VARCHAR(30)	NOT NULL,
	`log_time`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE `PAX` ADD CONSTRAINT `PK_PAX` PRIMARY KEY (
	`pax_uid`
);

ALTER TABLE `GS` ADD CONSTRAINT `PK_GS` PRIMARY KEY (
	`gs_id`
);

ALTER TABLE `CHKIN` ADD CONSTRAINT `PK_CHKIN` PRIMARY KEY (
	`chkin_id`
	ON DELETE CASCADE
);

ALTER TABLE `RSV` ADD CONSTRAINT `PK_RSV` PRIMARY KEY (
	`rsv_no`
	ON DELETE CASCADE
);

ALTER TABLE `CRAFT` ADD CONSTRAINT `PK_CRAFT` PRIMARY KEY (
	`craft_id`
	ON DELETE CASCADE
);

ALTER TABLE `LOG` ADD CONSTRAINT `PK_LOG` PRIMARY KEY (
	`log_id`
	ON DELETE CASCADE
);

